def show():
  print()
  print('                    .')
  print()
  print('                      .')
  print('            /^\\     .')
  print('       /\\   "V"')
  print('      /__\\   I      O  o')
  print('     //..\\\\  I     .')
  print('     \\].`[/  I')
  print('     /l\\/j\\  (]    .  O')
  print('    /. ~~ ,\\/I          .')
  print('    \\\\L__j^\\/I       o')
  print('     \\/--v}  I     o   .')
  print('     |    |  I   _________')
  print('     |    |  I c(`       \')o')
  print('     |    l  I   \\.     ,/')
  print('   _/j  L l\\_!  _//^---^\\\\_    -j0bz')
  print()